// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIjNDbfEtl3_ijXiLpBENUXAN-xrbo4I',
    appId: '1:937448018810:web:ea9ccd1532619bdd9a7cc3',
    messagingSenderId: '937448018810',
    projectId: 'first-9f9f4',
    authDomain: 'first-9f9f4.firebaseapp.com',
    storageBucket: 'first-9f9f4.firebasestorage.app',
    measurementId: 'G-Y6V9YDF563',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAhaNrSa0kqh-RyTkwMuFHeJUD5RZxouI',
    appId: '1:937448018810:android:8f686a199deb755f9a7cc3',
    messagingSenderId: '937448018810',
    projectId: 'first-9f9f4',
    storageBucket: 'first-9f9f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR3_eA-qgzbcjyQhLhMmaSVveQMiyn5bM',
    appId: '1:937448018810:ios:4dd0f2d31b5e2e929a7cc3',
    messagingSenderId: '937448018810',
    projectId: 'first-9f9f4',
    storageBucket: 'first-9f9f4.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR3_eA-qgzbcjyQhLhMmaSVveQMiyn5bM',
    appId: '1:937448018810:ios:4dd0f2d31b5e2e929a7cc3',
    messagingSenderId: '937448018810',
    projectId: 'first-9f9f4',
    storageBucket: 'first-9f9f4.firebasestorage.app',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIIjNDbfEtl3_ijXiLpBENUXAN-xrbo4I',
    appId: '1:937448018810:web:7936aa392e5ac9f19a7cc3',
    messagingSenderId: '937448018810',
    projectId: 'first-9f9f4',
    authDomain: 'first-9f9f4.firebaseapp.com',
    storageBucket: 'first-9f9f4.firebasestorage.app',
    measurementId: 'G-0JBDVZ4KW1',
  );
}
